# Generated by Django 4.1.3 on 2023-02-09 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('state', models.IntegerField(choices=[(1, 'BACKLOG'), (2, 'TO DO'), (3, 'DOING'), (4, 'TEST'), (5, 'DONE')])),
                ('priority', models.IntegerField(choices=[(1, 'HIGH'), (2, 'MEDIUM'), (1, 'LOW')])),
                ('deliver_date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
