# Generated by Django 4.1.3 on 2023-02-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drf',
            name='deliver_date',
            field=models.DateField(),
        ),
    ]
