# Generated by Django 4.1.3 on 2023-02-13 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0010_rename_state_drf_state_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drf',
            old_name='state_name',
            new_name='state',
        ),
    ]
