# Generated by Django 4.1.3 on 2023-02-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0011_rename_state_name_drf_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drf',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW')], max_length=20),
        ),
        migrations.AlterField(
            model_name='drf',
            name='state',
            field=models.CharField(choices=[('BACKLOG', 'BACKLOG'), ('TO DO', 'TO DO'), ('DOING', 'DOING'), ('TEST', 'TEST'), ('DONE', 'DONE')], max_length=20),
        ),
    ]
