# Generated by Django 4.1.3 on 2023-02-09 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0002_alter_drf_deliver_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drf',
            name='user',
        ),
    ]
