# Generated by Django 4.1.3 on 2023-02-13 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0009_alter_drf_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drf',
            old_name='state',
            new_name='state_name',
        ),
    ]
